<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Mini_E_Ticaret.Persistence</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Configurations\" />
    <Folder Include="Contexts\" />
    <Folder Include="Services\" />
    <Folder Include="Repositories\" />
  </ItemGroup>

</Project>
